site_name: Cloudy Stuff
site_url: https://cloudydev.net
theme:
  name: material
  font:
    #text: Lato
    #code: Inconsolata
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: max-dark
      toggle:
        icon: material/toggle-switch
        name: switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: max-lite
      toggle:
        icon: material/toggle-switch-off-outline
        name: switch to dark mode
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  #- javascripts/extra.js
markdown_extensions:
  - tables
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
    - Home: index.md
    - About Me: resume.md
    - Terraform: 
      - terraform-projects.md 
    - Unity3D: 
      - unity-projects.md
    - Cloud-Init:
      - Templates: https://github.com/buildstar-online/cloud-init-templates
      - Generator: https://github.com/buildstar-online/cloud-init-generator
      - PXEless: https://github.com/cloudymax/pxeless/
      - Scrap-Metal: https://github.com/cloudymax/Scrap-Metal
      - Kubevirt: https://github.com/small-hack/argocd-apps/tree/main/kubevirt
    - Other Projects:
      - Mod-Security Grafana Dashboard: https://github.com/cloudymax/modsecurity-dashboard/
      - Word-Art Generator: https://github.com/cloudymax/art_generator/
